on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run Docker container
      id: hello 
      uses: ./
      with:
        MYINPUT: "Hello from the workflow!"
    - name: Get output from container action
      run: echo "Memory info from container: ${{ steps.hello.outputs.MyOutput }}"

  